name: "yaml_modify"
description: "A library for modify yaml files, for example you can modify pubspec.yaml by this library"
homepage: "https://github.com/luuillu/yaml_modify"

version: "0.1.3"
dependencies:
  quiver: "^2.1.3"
  yaml: "^2.2.1"

dev_dependencies:
  test: "^1.15.1"

environment:
  sdk: ">=2.1.0 <3.0.0"
